Update Issues section with the NoClassDefFoundError/ClassNotFoundException thrown by Apache Geode due to class resolution issues with embedded/nested libs contained in the Spring Boot 'executable' JAR file.